### ISSUE TITLE
is player head dupe glitch still exists?

### ISSUE THREAD

**Issue by candrawardana** [JEFF-Media-GbR/Spigot-AngelChestPlus#23]
>have player head in inventories
>death
>use angel chest
>the head get dupes

**Comment by mfnalex** [comment]
A bit more information would be helpful.

E.g. the output of:

/version
/version AngelChest

**Comment by mfnalex** [comment]
BTW is this a question or a real bug report?

If it's a questions: **There currently is not a single reported duplication bug.**

If it's a bug report: Please provide more information, see above. Closed until further reply.

**Comment by Cazcez** [comment]
If it's a question i gave a head to myself and tried. There is no dupe
