### ISSUE TITLE
server crash with angle chest free on 1.17 when trying to open a angle chest

### ISSUE THREAD

**Issue by hitroll2121** [JEFF-Media-GbR/Spigot-AngelChestPlus#29]
when you try to get the items from an angle chest in spigot 1.17 when your inventory doesn't have enough space for all items the server will crash crash log Pastebin https://pastebin.com/mgSepWZy

**Comment by mfnalex** [comment]
What's the output of /version and /version angelchest ?

**Comment by hitroll2121** [comment]
For /version output is This server is running CraftBukkit version 3103-Spigot-a09c0bb-4d2c780 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) for /version angelchest AngelChest version 3.28.1
17.06 10:34:51 [Server] Server thread/INFO Best available death chest / grave plugin!
17.06 10:34:51 [Server] Server thread/INFO Website: https://www.spigotmc.org/resources/angelchestplus.88214/
17.06 10:34:51 [Server] Server thread/INFO Authors: mfnalex and JEFF Media GbR

**Comment by mfnalex** [comment]
It's a spigot bug. Update to latest Spigot (should be build 3149 AFAIK) and let me know if it fixes it

**Comment by mfnalex** [comment]
no reply in a week, was probably a spigot bug, let me know if you have any new information
